id = "obsidian-sunset"
name = "Obsidian Sunset Theme"
version = "0.0.1"
schema_version = 1
authors = ["Łukasz Czerniawski <l.czerniawski@icloud.com>"]
description = "Obsidian Sunset is a dark and colorful theme for Zed that enhances the readability and aesthetics of your code."
repository = "https://github.com/lczerniawski/ObsidianSunset-Zed"
